In [1]:
!ls

__notebook__.ipynb

In [2]:
!pip install ../input/mtcnn-package/mtcnn-0.1.0-py3-none-any.whl

Processing /kaggle/input/mtcnn-package/mtcnn-0.1.0-py3-none-any.whl
Requirement already satisfied: opencv-python>=4.1.0 in /opt/conda/lib/python3.6/site-packages (from mtcnn==0.1.0) (4.1.2.30)
Requirement already satisfied: keras>=2.0.0 in /opt/conda/lib/python3.6/site-packages (from mtcnn==0.1.0) (2.3.1)
Requirement already satisfied: numpy>=1.11.3 in /opt/conda/lib/python3.6/site-packages (from opencv-python>=4.1.0->mtcnn==0.1.0) (1.17.4)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.6/site-packages (from keras>=2.0.0->mtcnn==0.1.0) (1.13.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.6/site-packages (from keras>=2.0.0->mtcnn==0.1.0) (5.1.2)
Requirement already satisfied: keras-applications>=1.0.6 in /opt/conda/lib/python3.6/site-packages (from keras>=2.0.0->mtcnn==0.1.0) (1.0.8)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /opt/conda/lib/python3.6/site-packages (from keras>=2.0.0->mtcnn==0.1.0) (1.1.0)
Requirement already satisfied: scipy>=0.14 in /opt/conda/lib/python3.6/site-packages (from keras>=2.0.0->mtcnn==0.1.0) (1.3.3)
Requirement already satisfied: h5py in /opt/conda/lib/python3.6/site-packages (from keras>=2.0.0->mtcnn==0.1.0) (2.9.0)
Installing collected packages: mtcnn
Successfully installed mtcnn-0.1.0

In [3]:
import sys
import numpy as np
import pandas as pd
import cv2
from keras.optimizers import Adam, SGD
from tqdm.notebook import tqdm
import glob
from mtcnn import MTCNN

# use shutil to copy file from input folder to working folder
#from shutil import copyfile

Using TensorFlow backend.

In [4]:
# -*- coding:utf-8 -*-

from keras.models import Model as KerasModel
from keras.layers import Input, Dense, Flatten, Conv2D, MaxPooling2D, BatchNormalization, Dropout, Reshape, Concatenate, LeakyReLU
from keras.optimizers import Adam

IMGWIDTH = 256

class Classifier:
    def __init__():
        self.model = 0
    
    def predict(self, x):
        return self.model.predict(x)
    
    def fit(self, x, y):
        return self.model.train_on_batch(x, y)
    
    def get_accuracy(self, x, y):
        return self.model.test_on_batch(x, y)
    
    def load(self, path):
        self.model.load_weights(path)


class Meso1(Classifier):
    """
    Feature extraction + Classification
    """
    def __init__(self, learning_rate = 0.001, dl_rate = 1):
        self.model = self.init_model(dl_rate)
        optimizer = Adam(lr = learning_rate)
        self.model.compile(optimizer = optimizer, loss = 'mean_squared_error', metrics = ['accuracy'])
    
    def init_model(self, dl_rate):
        x = Input(shape = (IMGWIDTH, IMGWIDTH, 3))
        
        x1 = Conv2D(16, (3, 3), dilation_rate = dl_rate, strides = 1, padding='same', activation = 'relu')(x)
        x1 = Conv2D(4, (1, 1), padding='same', activation = 'relu')(x1)
        x1 = BatchNormalization()(x1)
        x1 = MaxPooling2D(pool_size=(8, 8), padding='same')(x1)

        y = Flatten()(x1)
        y = Dropout(0.5)(y)
        y = Dense(1, activation = 'sigmoid')(y)
        return KerasModel(inputs = x, outputs = y)


class Meso4(Classifier):
    def __init__(self, learning_rate = 0.001):
        self.model = self.init_model()
        optimizer = Adam(lr = learning_rate)
        self.model.compile(optimizer = optimizer, loss = 'mean_squared_error', metrics = ['accuracy'])
    
    def init_model(self): 
        x = Input(shape = (IMGWIDTH, IMGWIDTH, 3))
        
        x1 = Conv2D(8, (3, 3), padding='same', activation = 'relu')(x)
        x1 = BatchNormalization()(x1)
        x1 = MaxPooling2D(pool_size=(2, 2), padding='same')(x1)
        
        x2 = Conv2D(8, (5, 5), padding='same', activation = 'relu')(x1)
        x2 = BatchNormalization()(x2)
        x2 = MaxPooling2D(pool_size=(2, 2), padding='same')(x2)
        
        x3 = Conv2D(16, (5, 5), padding='same', activation = 'relu')(x2)
        x3 = BatchNormalization()(x3)
        x3 = MaxPooling2D(pool_size=(2, 2), padding='same')(x3)
        
        x4 = Conv2D(16, (5, 5), padding='same', activation = 'relu')(x3)
        x4 = BatchNormalization()(x4)
        x4 = MaxPooling2D(pool_size=(4, 4), padding='same')(x4)
        
        y = Flatten()(x4)
        y = Dropout(0.5)(y)
        y = Dense(16)(y)
        y = LeakyReLU(alpha=0.1)(y)
        y = Dropout(0.5)(y)
        y = Dense(1, activation = 'sigmoid')(y)

        return KerasModel(inputs = x, outputs = y)


class MesoInception4(Classifier):
    def __init__(self, learning_rate = 0.001):
        self.model = self.init_model()
        optimizer = Adam(lr = learning_rate)
        self.model.compile(optimizer = optimizer, loss = 'mean_squared_error', metrics = ['accuracy'])
    
    def InceptionLayer(self, a, b, c, d):
        def func(x):
            x1 = Conv2D(a, (1, 1), padding='same', activation='relu')(x)
            
            x2 = Conv2D(b, (1, 1), padding='same', activation='relu')(x)
            x2 = Conv2D(b, (3, 3), padding='same', activation='relu')(x2)
            
            x3 = Conv2D(c, (1, 1), padding='same', activation='relu')(x)
            x3 = Conv2D(c, (3, 3), dilation_rate = 2, strides = 1, padding='same', activation='relu')(x3)
            
            x4 = Conv2D(d, (1, 1), padding='same', activation='relu')(x)
            x4 = Conv2D(d, (3, 3), dilation_rate = 3, strides = 1, padding='same', activation='relu')(x4)

            y = Concatenate(axis = -1)([x1, x2, x3, x4])
            
            return y
        return func
    
    def init_model(self):
        x = Input(shape = (IMGWIDTH, IMGWIDTH, 3))
        
        x1 = self.InceptionLayer(1, 4, 4, 2)(x)
        x1 = BatchNormalization()(x1)
        x1 = MaxPooling2D(pool_size=(2, 2), padding='same')(x1)
        
        x2 = self.InceptionLayer(2, 4, 4, 2)(x1)
        x2 = BatchNormalization()(x2)
        x2 = MaxPooling2D(pool_size=(2, 2), padding='same')(x2)        
        
        x3 = Conv2D(16, (5, 5), padding='same', activation = 'relu')(x2)
        x3 = BatchNormalization()(x3)
        x3 = MaxPooling2D(pool_size=(2, 2), padding='same')(x3)
        
        x4 = Conv2D(16, (5, 5), padding='same', activation = 'relu')(x3)
        x4 = BatchNormalization()(x4)
        x4 = MaxPooling2D(pool_size=(4, 4), padding='same')(x4)
        
        y = Flatten()(x4)
        y = Dropout(0.5)(y)
        y = Dense(16)(y)
        y = LeakyReLU(alpha=0.1)(y)
        y = Dropout(0.5)(y)
        y = Dense(1, activation = 'sigmoid')(y)

        return KerasModel(inputs = x, outputs = y)

In [5]:
"""""# -*- coding:utf-8 -*-
# Darius' approach -This generates a batch of nearly 50 frames per scene. And makes predictions on these frames.But the kernel goes out after using it. 

import random
from os import listdir
from os.path import isfile, join

import numpy as np
from math import floor
from scipy.ndimage.interpolation import zoom, rotate

import imageio
import face_recognition


## Face extraction

class Video:
    def __init__(self, path):
        self.path = path
        self.container = imageio.get_reader(path, 'ffmpeg')
        self.length = self.container.count_frames()
        self.fps = self.container.get_meta_data()['fps']
    
    def init_head(self):
        self.container.set_image_index(0)
    
    def next_frame(self):
        self.container.get_next_data()
    
    def get(self, key):
        return self.container.get_data(key)
    
    def __call__(self, key):
        return self.get(key)
    
    def __len__(self):
        return self.length


class FaceFinder(Video):
    def __init__(self, path, load_first_face = True):
        super().__init__(path)
        self.faces = {}
        self.coordinates = {}  # stores the face (locations center, rotation, length)
        self.last_frame = self.get(0)
        self.frame_shape = self.last_frame.shape[:2]
        self.last_location = (0, 200, 200, 0)
        if (load_first_face):
            face_positions = face_recognition.face_locations(self.last_frame, number_of_times_to_upsample=2)
            if len(face_positions) > 0:
                self.last_location = face_positions[0]
    
    def load_coordinates(self, filename):
        np_coords = np.load(filename)
        self.coordinates = np_coords.item()
    
    def expand_location_zone(self, loc, margin = 0.2):
        ''' Adds a margin around a frame slice '''
        offset = round(margin * (loc[2] - loc[0]))
        y0 = max(loc[0] - offset, 0)
        x1 = min(loc[1] + offset, self.frame_shape[1])
        y1 = min(loc[2] + offset, self.frame_shape[0])
        x0 = max(loc[3] - offset, 0)
        return (y0, x1, y1, x0)
    
    @staticmethod
    def upsample_location(reduced_location, upsampled_origin, factor):
        ''' Adapt a location to an upsampled image slice '''
        y0, x1, y1, x0 = reduced_location
        Y0 = round(upsampled_origin[0] + y0 * factor)
        X1 = round(upsampled_origin[1] + x1 * factor)
        Y1 = round(upsampled_origin[0] + y1 * factor)
        X0 = round(upsampled_origin[1] + x0 * factor)
        return (Y0, X1, Y1, X0)

    @staticmethod
    def pop_largest_location(location_list):
        max_location = location_list[0]
        max_size = 0
        if len(location_list) > 1:
            for location in location_list:
                size = location[2] - location[0]
                if size > max_size:
                    max_size = size
                    max_location = location
        return max_location
    
    @staticmethod
    def L2(A, B):
        return np.sqrt(np.sum(np.square(A - B)))
    
    def find_coordinates(self, landmark, K = 2.2):
        '''
        We either choose K * distance(eyes, mouth),
        or, if the head is tilted, K * distance(eye 1, eye 2)
        /!\ landmarks coordinates are in (x,y) not (y,x)
        '''
        E1 = np.mean(landmark['left_eye'], axis=0)
        E2 = np.mean(landmark['right_eye'], axis=0)
        E = (E1 + E2) / 2
        N = np.mean(landmark['nose_tip'], axis=0) / 2 + np.mean(landmark['nose_bridge'], axis=0) / 2
        B1 = np.mean(landmark['top_lip'], axis=0)
        B2 = np.mean(landmark['bottom_lip'], axis=0)
        B = (B1 + B2) / 2

        C = N
        l1 = self.L2(E1, E2)
        l2 = self.L2(B, E)
        l = max(l1, l2) * K
        if (B[1] == E[1]):
            if (B[0] > E[0]):
                rot = 90
            else:
                rot = -90
        else:
            rot = np.arctan((B[0] - E[0]) / (B[1] - E[1])) / np.pi * 180
        
        return ((floor(C[1]), floor(C[0])), floor(l), rot)
    
    
    def find_faces(self, resize = 0.5, stop = 0, skipstep = 0, no_face_acceleration_threshold = 3, cut_left = 0, cut_right = -1, use_frameset = False, frameset = []):
        '''
        The core function to extract faces from frames
        using previous frame location and downsampling to accelerate the loop.
        '''
        not_found = 0
        no_face = 0
        no_face_acc = 0
        
        # to only deal with a subset of a video, for instance I-frames only
        if (use_frameset):
            finder_frameset = frameset
        else:
            if (stop != 0):
                finder_frameset = range(0, min(self.length, stop), skipstep + 1)
            else:
                finder_frameset = range(0, self.length, skipstep + 1)
        
        # Quick face finder loop
        for i in finder_frameset:
            # Get frame
            frame = self.get(i)
            if (cut_left != 0 or cut_right != -1):
                frame[:, :cut_left] = 0
                frame[:, cut_right:] = 0            
            
            # Find face in the previously found zone
            potential_location = self.expand_location_zone(self.last_location)
            potential_face_patch = frame[potential_location[0]:potential_location[2], potential_location[3]:potential_location[1]]
            potential_face_patch_origin = (potential_location[0], potential_location[3])
    
            reduced_potential_face_patch = zoom(potential_face_patch, (resize, resize, 1))
            reduced_face_locations = face_recognition.face_locations(reduced_potential_face_patch, model = 'cnn')
            
            if len(reduced_face_locations) > 0:
                no_face_acc = 0  # reset the no_face_acceleration mode accumulator

                reduced_face_location = self.pop_largest_location(reduced_face_locations)
                face_location = self.upsample_location(reduced_face_location,
                                                    potential_face_patch_origin,
                                                    1 / resize)
                self.faces[i] = face_location
                self.last_location = face_location
                
                # extract face rotation, length and center from landmarks
                landmarks = face_recognition.face_landmarks(frame, [face_location])
                if len(landmarks) > 0:
                    # we assume that there is one and only one landmark group
                    self.coordinates[i] = self.find_coordinates(landmarks[0])
            else:
                not_found += 1

                if no_face_acc < no_face_acceleration_threshold:
                    # Look for face in full frame
                    face_locations = face_recognition.face_locations(frame, number_of_times_to_upsample = 2)
                else:
                    # Avoid spending to much time on a long scene without faces
                    reduced_frame = zoom(frame, (resize, resize, 1))
                    face_locations = face_recognition.face_locations(reduced_frame)
                    
                if len(face_locations) > 0:
                    print('Face extraction warning : ', i, '- found face in full frame', face_locations)
                    no_face_acc = 0  # reset the no_face_acceleration mode accumulator
                    
                    face_location = self.pop_largest_location(face_locations)
                    
                    # if was found on a reduced frame, upsample location
                    if no_face_acc > no_face_acceleration_threshold:
                        face_location = self.upsample_location(face_location, (0, 0), 1 / resize)
                    
                    self.faces[i] = face_location
                    self.last_location = face_location
                    
                    # extract face rotation, length and center from landmarks
                    landmarks = face_recognition.face_landmarks(frame, [face_location])
                    if len(landmarks) > 0:
                        self.coordinates[i] = self.find_coordinates(landmarks[0])
                else:
                    print('Face extraction warning : ',i, '- no face')
                    no_face_acc += 1
                    no_face += 1

        print('Face extraction report of', 'not_found :', not_found)
        print('Face extraction report of', 'no_face :', no_face)
        return 0
    
    def get_face(self, i):
        ''' Basic unused face extraction without alignment '''
        frame = self.get(i)
        if i in self.faces:
            loc = self.faces[i]
            patch = frame[loc[0]:loc[2], loc[3]:loc[1]]
            return patch
        return frame
    
    @staticmethod
    def get_image_slice(img, y0, y1, x0, x1):
        '''Get values outside the domain of an image'''
        m, n = img.shape[:2]
        padding = max(-y0, y1-m, -x0, x1-n, 0)
        padded_img = np.pad(img, ((padding, padding), (padding, padding), (0, 0)), 'reflect')
        return padded_img[(padding + y0):(padding + y1),
                        (padding + x0):(padding + x1)]
    
    def get_aligned_face(self, i, l_factor = 1.3):
        '''
        The second core function that converts the data from self.coordinates into an face image.
        '''
        frame = self.get(i)
        if i in self.coordinates:
            c, l, r = self.coordinates[i]
            l = int(l) * l_factor # fine-tuning the face zoom we really want
            dl_ = floor(np.sqrt(2) * l / 2) # largest zone even when rotated
            patch = self.get_image_slice(frame,
                                    floor(c[0] - dl_),
                                    floor(c[0] + dl_),
                                    floor(c[1] - dl_),
                                    floor(c[1] + dl_))
            rotated_patch = rotate(patch, -r, reshape=False)
            # note : dl_ is the center of the patch of length 2dl_
            return self.get_image_slice(rotated_patch,
                                    floor(dl_-l//2),
                                    floor(dl_+l//2),
                                    floor(dl_-l//2),
                                    floor(dl_+l//2))
        return frame


## Face prediction

class FaceBatchGenerator:
    '''
    Made to deal with framesubsets of video.
    '''
    def __init__(self, face_finder, target_size = 256):
        self.finder = face_finder
        self.target_size = target_size
        self.head = 0
        self.length = int(face_finder.length)

    def resize_patch(self, patch):
        m, n = patch.shape[:2]
        return zoom(patch, (self.target_size / m, self.target_size / n, 1))
    
    def next_batch(self, batch_size = 50):
        batch = np.zeros((1, self.target_size, self.target_size, 3))
        stop = min(self.head + batch_size, self.length)
        i = 0
        while (i < batch_size) and (self.head < self.length):
            if self.head in self.finder.coordinates:
                patch = self.finder.get_aligned_face(self.head)
                batch = np.concatenate((batch, np.expand_dims(self.resize_patch(patch), axis = 0)),
                                        axis = 0)
                i += 1
            self.head += 1
        return batch[1:]


def predict_faces(generator, classifier, batch_size = 50, output_size = 1):
    '''
    Compute predictions for a face batch generator
    '''
    n = len(generator.finder.coordinates.items())
    profile = np.zeros((1, output_size))
    for epoch in range(n // batch_size + 1):
        face_batch = generator.next_batch(batch_size = batch_size)
        prediction = classifier.predict(face_batch)
        if (len(prediction) > 0):
            profile = np.concatenate((profile, prediction))
    return profile[1:]


def compute_accuracy(classifier, dirname, frame_subsample_count = 30):
    '''
    Extraction + Prediction over a video
    '''
    filenames = [f for f in listdir(dirname) if isfile(join(dirname, f)) and ((f[-4:] == '.mp4') or (f[-4:] == '.avi') or (f[-4:] == '.mov'))]
    predictions = {}
    
    for vid in filenames:
        print('Dealing with video ', vid)
        
        # Compute face locations and store them in the face finder
        face_finder = FaceFinder(join(dirname, vid), load_first_face = False)
        skipstep = max(floor(face_finder.length / frame_subsample_count), 0)
        face_finder.find_faces(resize=0.5, skipstep = skipstep)
        
        print('Predicting ', vid)
        gen = FaceBatchGenerator(face_finder)
        p = predict_faces(gen, classifier)
        
        predictions[vid[:-4]] = (np.mean(p > 0.5), p)
    return predictions"""""

'""# -*- coding:utf-8 -*-\n# Darius\' approach -This generates a batch of nearly 50 frames per scene. And makes predictions on these frames.But the kernel goes out after using it. \n\nimport random\nfrom os import listdir\nfrom os.path import isfile, join\n\nimport numpy as np\nfrom math import floor\nfrom scipy.ndimage.interpolation import zoom, rotate\n\nimport imageio\nimport face_recognition\n\n\n## Face extraction\n\nclass Video:\n    def __init__(self, path):\n        self.path = path\n        self.container = imageio.get_reader(path, \'ffmpeg\')\n        self.length = self.container.count_frames()\n        self.fps = self.container.get_meta_data()[\'fps\']\n    \n    def init_head(self):\n        self.container.set_image_index(0)\n    \n    def next_frame(self):\n        self.container.get_next_data()\n    \n    def get(self, key):\n        return self.container.get_data(key)\n    \n    def __call__(self, key):\n        return self.get(key)\n    \n    def __len__(self):\n        return self.length\n\n\nclass FaceFinder(Video):\n    def __init__(self, path, load_first_face = True):\n        super().__init__(path)\n        self.faces = {}\n        self.coordinates = {}  # stores the face (locations center, rotation, length)\n        self.last_frame = self.get(0)\n        self.frame_shape = self.last_frame.shape[:2]\n        self.last_location = (0, 200, 200, 0)\n        if (load_first_face):\n            face_positions = face_recognition.face_locations(self.last_frame, number_of_times_to_upsample=2)\n            if len(face_positions) > 0:\n                self.last_location = face_positions[0]\n    \n    def load_coordinates(self, filename):\n        np_coords = np.load(filename)\n        self.coordinates = np_coords.item()\n    \n    def expand_location_zone(self, loc, margin = 0.2):\n        \'\'\' Adds a margin around a frame slice \'\'\'\n        offset = round(margin * (loc[2] - loc[0]))\n        y0 = max(loc[0] - offset, 0)\n        x1 = min(loc[1] + offset, self.frame_shape[1])\n        y1 = min(loc[2] + offset, self.frame_shape[0])\n        x0 = max(loc[3] - offset, 0)\n        return (y0, x1, y1, x0)\n    \n    @staticmethod\n    def upsample_location(reduced_location, upsampled_origin, factor):\n        \'\'\' Adapt a location to an upsampled image slice \'\'\'\n        y0, x1, y1, x0 = reduced_location\n        Y0 = round(upsampled_origin[0] + y0 * factor)\n        X1 = round(upsampled_origin[1] + x1 * factor)\n        Y1 = round(upsampled_origin[0] + y1 * factor)\n        X0 = round(upsampled_origin[1] + x0 * factor)\n        return (Y0, X1, Y1, X0)\n\n    @staticmethod\n    def pop_largest_location(location_list):\n        max_location = location_list[0]\n        max_size = 0\n        if len(location_list) > 1:\n            for location in location_list:\n                size = location[2] - location[0]\n                if size > max_size:\n                    max_size = size\n                    max_location = location\n        return max_location\n    \n    @staticmethod\n    def L2(A, B):\n        return np.sqrt(np.sum(np.square(A - B)))\n    \n    def find_coordinates(self, landmark, K = 2.2):\n        \'\'\'\n        We either choose K * distance(eyes, mouth),\n        or, if the head is tilted, K * distance(eye 1, eye 2)\n        /!\\ landmarks coordinates are in (x,y) not (y,x)\n        \'\'\'\n        E1 = np.mean(landmark[\'left_eye\'], axis=0)\n        E2 = np.mean(landmark[\'right_eye\'], axis=0)\n        E = (E1 + E2) / 2\n        N = np.mean(landmark[\'nose_tip\'], axis=0) / 2 + np.mean(landmark[\'nose_bridge\'], axis=0) / 2\n        B1 = np.mean(landmark[\'top_lip\'], axis=0)\n        B2 = np.mean(landmark[\'bottom_lip\'], axis=0)\n        B = (B1 + B2) / 2\n\n        C = N\n        l1 = self.L2(E1, E2)\n        l2 = self.L2(B, E)\n        l = max(l1, l2) * K\n        if (B[1] == E[1]):\n            if (B[0] > E[0]):\n                rot = 90\n            else:\n                rot = -90\n        else:\n            rot = np.arctan((B[0] - E[0]) / (B[1] - E[1])) / np.pi * 180\n        \n        return ((floor(C[1]), floor(C[0])), floor(l), rot)\n    \n    \n    def find_faces(self, resize = 0.5, stop = 0, skipstep = 0, no_face_acceleration_threshold = 3, cut_left = 0, cut_right = -1, use_frameset = False, frameset = []):\n        \'\'\'\n        The core function to extract faces from frames\n        using previous frame location and downsampling to accelerate the loop.\n        \'\'\'\n        not_found = 0\n        no_face = 0\n        no_face_acc = 0\n        \n        # to only deal with a subset of a video, for instance I-frames only\n        if (use_frameset):\n            finder_frameset = frameset\n        else:\n            if (stop != 0):\n                finder_frameset = range(0, min(self.length, stop), skipstep + 1)\n            else:\n                finder_frameset = range(0, self.length, skipstep + 1)\n        \n        # Quick face finder loop\n        for i in finder_frameset:\n            # Get frame\n            frame = self.get(i)\n            if (cut_left != 0 or cut_right != -1):\n                frame[:, :cut_left] = 0\n                frame[:, cut_right:] = 0            \n            \n            # Find face in the previously found zone\n            potential_location = self.expand_location_zone(self.last_location)\n            potential_face_patch = frame[potential_location[0]:potential_location[2], potential_location[3]:potential_location[1]]\n            potential_face_patch_origin = (potential_location[0], potential_location[3])\n    \n            reduced_potential_face_patch = zoom(potential_face_patch, (resize, resize, 1))\n            reduced_face_locations = face_recognition.face_locations(reduced_potential_face_patch, model = \'cnn\')\n            \n            if len(reduced_face_locations) > 0:\n                no_face_acc = 0  # reset the no_face_acceleration mode accumulator\n\n                reduced_face_location = self.pop_largest_location(reduced_face_locations)\n                face_location = self.upsample_location(reduced_face_location,\n                                                    potential_face_patch_origin,\n                                                    1 / resize)\n                self.faces[i] = face_location\n                self.last_location = face_location\n                \n                # extract face rotation, length and center from landmarks\n                landmarks = face_recognition.face_landmarks(frame, [face_location])\n                if len(landmarks) > 0:\n                    # we assume that there is one and only one landmark group\n                    self.coordinates[i] = self.find_coordinates(landmarks[0])\n            else:\n                not_found += 1\n\n                if no_face_acc < no_face_acceleration_threshold:\n                    # Look for face in full frame\n                    face_locations = face_recognition.face_locations(frame, number_of_times_to_upsample = 2)\n                else:\n                    # Avoid spending to much time on a long scene without faces\n                    reduced_frame = zoom(frame, (resize, resize, 1))\n                    face_locations = face_recognition.face_locations(reduced_frame)\n                    \n                if len(face_locations) > 0:\n                    print(\'Face extraction warning : \', i, \'- found face in full frame\', face_locations)\n                    no_face_acc = 0  # reset the no_face_acceleration mode accumulator\n                    \n                    face_location = self.pop_largest_location(face_locations)\n                    \n                    # if was found on a reduced frame, upsample location\n                    if no_face_acc > no_face_acceleration_threshold:\n                        face_location = self.upsample_location(face_location, (0, 0), 1 / resize)\n                    \n                    self.faces[i] = face_location\n                    self.last_location = face_location\n                    \n                    # extract face rotation, length and center from landmarks\n                    landmarks = face_recognition.face_landmarks(frame, [face_location])\n                    if len(landmarks) > 0:\n                        self.coordinates[i] = self.find_coordinates(landmarks[0])\n                else:\n                    print(\'Face extraction warning : \',i, \'- no face\')\n                    no_face_acc += 1\n                    no_face += 1\n\n        print(\'Face extraction report of\', \'not_found :\', not_found)\n        print(\'Face extraction report of\', \'no_face :\', no_face)\n        return 0\n    \n    def get_face(self, i):\n        \'\'\' Basic unused face extraction without alignment \'\'\'\n        frame = self.get(i)\n        if i in self.faces:\n            loc = self.faces[i]\n            patch = frame[loc[0]:loc[2], loc[3]:loc[1]]\n            return patch\n        return frame\n    \n    @staticmethod\n    def get_image_slice(img, y0, y1, x0, x1):\n        \'\'\'Get values outside the domain of an image\'\'\'\n        m, n = img.shape[:2]\n        padding = max(-y0, y1-m, -x0, x1-n, 0)\n        padded_img = np.pad(img, ((padding, padding), (padding, padding), (0, 0)), \'reflect\')\n        return padded_img[(padding + y0):(padding + y1),\n                        (padding + x0):(padding + x1)]\n    \n    def get_aligned_face(self, i, l_factor = 1.3):\n        \'\'\'\n        The second core function that converts the data from self.coordinates into an face image.\n        \'\'\'\n        frame = self.get(i)\n        if i in self.coordinates:\n            c, l, r = self.coordinates[i]\n            l = int(l) * l_factor # fine-tuning the face zoom we really want\n            dl_ = floor(np.sqrt(2) * l / 2) # largest zone even when rotated\n            patch = self.get_image_slice(frame,\n                                    floor(c[0] - dl_),\n                                    floor(c[0] + dl_),\n                                    floor(c[1] - dl_),\n                                    floor(c[1] + dl_))\n            rotated_patch = rotate(patch, -r, reshape=False)\n            # note : dl_ is the center of the patch of length 2dl_\n            return self.get_image_slice(rotated_patch,\n                                    floor(dl_-l//2),\n                                    floor(dl_+l//2),\n                                    floor(dl_-l//2),\n                                    floor(dl_+l//2))\n        return frame\n\n\n## Face prediction\n\nclass FaceBatchGenerator:\n    \'\'\'\n    Made to deal with framesubsets of video.\n    \'\'\'\n    def __init__(self, face_finder, target_size = 256):\n        self.finder = face_finder\n        self.target_size = target_size\n        self.head = 0\n        self.length = int(face_finder.length)\n\n    def resize_patch(self, patch):\n        m, n = patch.shape[:2]\n        return zoom(patch, (self.target_size / m, self.target_size / n, 1))\n    \n    def next_batch(self, batch_size = 50):\n        batch = np.zeros((1, self.target_size, self.target_size, 3))\n        stop = min(self.head + batch_size, self.length)\n        i = 0\n        while (i < batch_size) and (self.head < self.length):\n            if self.head in self.finder.coordinates:\n                patch = self.finder.get_aligned_face(self.head)\n                batch = np.concatenate((batch, np.expand_dims(self.resize_patch(patch), axis = 0)),\n                                        axis = 0)\n                i += 1\n            self.head += 1\n        return batch[1:]\n\n\ndef predict_faces(generator, classifier, batch_size = 50, output_size = 1):\n    \'\'\'\n    Compute predictions for a face batch generator\n    \'\'\'\n    n = len(generator.finder.coordinates.items())\n    profile = np.zeros((1, output_size))\n    for epoch in range(n // batch_size + 1):\n        face_batch = generator.next_batch(batch_size = batch_size)\n        prediction = classifier.predict(face_batch)\n        if (len(prediction) > 0):\n            profile = np.concatenate((profile, prediction))\n    return profile[1:]\n\n\ndef compute_accuracy(classifier, dirname, frame_subsample_count = 30):\n    \'\'\'\n    Extraction + Prediction over a video\n    \'\'\'\n    filenames = [f for f in listdir(dirname) if isfile(join(dirname, f)) and ((f[-4:] == \'.mp4\') or (f[-4:] == \'.avi\') or (f[-4:] == \'.mov\'))]\n    predictions = {}\n    \n    for vid in filenames:\n        print(\'Dealing with video \', vid)\n        \n        # Compute face locations and store them in the face finder\n        face_finder = FaceFinder(join(dirname, vid), load_first_face = False)\n        skipstep = max(floor(face_finder.length / frame_subsample_count), 0)\n        face_finder.find_faces(resize=0.5, skipstep = skipstep)\n        \n        print(\'Predicting \', vid)\n        gen = FaceBatchGenerator(face_finder)\n        p = predict_faces(gen, classifier)\n        \n        predictions[vid[:-4]] = (np.mean(p > 0.5), p)\n    return predictions'

In [6]:
INPUT = "/kaggle/input/deepfake-detection-challenge"
MAX_SKIP = 10
NUM_FRAME= 150
LR_ALPHA = 1e-3

In [7]:
import os
test_dir = os.path.join(INPUT, "test_videos/")
filenames = os.listdir(test_dir)
prediction_filenames = filenames
test_video_files = [os.path.join(test_dir, fn) for fn in filenames]

print(test_video_files[:2])

['/kaggle/input/deepfake-detection-challenge/test_videos/nymodlmxni.mp4', '/kaggle/input/deepfake-detection-challenge/test_videos/oaguiggjyv.mp4']

In [8]:
detector = MTCNN()

def detect_face(image):
    # convert to RGB for MTCNN use
    img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    final = []
    detected_faces_raw = detector.detect_faces(img)

    # check if any faces detected
    if not detected_faces_raw:
        #print("no faces")
        return []
    
    # store confidences & bounding box
    confidences = []
    for n in detected_faces_raw:
        x, y, w, h = n["box"]
        final.append([x, y, w, h])
        confidences.append(n["confidence"])
        pass
    # check if detector is confident that this is a face
    if max(confidences) < 0.7:
        return []
    # get the most confident detected face bounding box
    max_conf_coord = final[confidences.index(max(confidences))]
    
    return max_conf_coord


def crop(image, x, y, w, h):
    # enlarge bounding box to ensure containing the fucking face
    x -= 40
    y -= 40
    w += 80
    h += 80
    if x < 0: x = 0
    if y <= 0: y = 0
    
    crop = image[y : y + h, x : x + w, :]
    crop = cv2.resize(crop, (256, 256))
    return cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)

def detect_video(video):
    # extract the middle frame of a video
    camera = cv2.VideoCapture(video)
    camera.set(1, NUM_FRAME)
    success, vframe = camera.read()
    
    # convert color to RGB & detect face
    vframe = cv2.cvtColor(vframe, cv2.COLOR_BGR2RGB)
    bounding_box = detect_face(vframe)
    
    # deal with no faces, try the following 10 frames to detect bounding box
    if not bounding_box:
        count = 0
        current = NUM_FRAME
        
        for i in range(NUM_FRAME + 1, NUM_FRAME + 11):
            success, vframe = camera.read()
            vframe = cv2.cvtColor(vframe, cv2.COLOR_BGR2RGB)
            bounding_box = detect_face(vframe)
            # check if getting a face
            if len(bounding_box) != 0:
                break
        # check if still no face detected
        if not bounding_box:
            print("no face found")
            prediction_filenames.remove(video.replace(test_dir,''))
            return None
    
    # got a face
    x, y, w, h = bounding_box
    camera.release()
    return crop(vframe, x, y, w, h)

In [9]:
!ls

__notebook__.ipynb

In [10]:
# generate test_X
test_X = []
no_face = []
with_face = []
#for video in tqdm(test_video_files[:32]):
for noface,video in tqdm(enumerate(test_video_files)):
    cou = detect_video(video)
    # if no face found
    if cou is None:
        no_face.append(noface)
        continue
    test_X.append(cou)
    with_face.append(noface)
    pass

# convert test_X to array
test_X = np.array(test_X)

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found
no face found

In [11]:
!ls

__notebook__.ipynb

In [12]:
!mkdir test_images

In [13]:
%cd test_images

/kaggle/working/test_images

In [14]:
%mkdir image_class

In [15]:
%cd image_class

/kaggle/working/test_images/image_class

In [16]:
from PIL import Image
import numpy as np

for i,x in enumerate(test_X):
    w, h = 256, 256
    img = Image.fromarray(x, 'RGB')
    img.save(str(i)+ ".jpg" )
    img.show()

In [17]:
!ls

0.jpg	 135.jpg  172.jpg  209.jpg  246.jpg  283.jpg  32.jpg   357.jpg	67.jpg
1.jpg	 136.jpg  173.jpg  21.jpg   247.jpg  284.jpg  320.jpg  358.jpg	68.jpg
10.jpg	 137.jpg  174.jpg  210.jpg  248.jpg  285.jpg  321.jpg  359.jpg	69.jpg
100.jpg  138.jpg  175.jpg  211.jpg  249.jpg  286.jpg  322.jpg  36.jpg	7.jpg
101.jpg  139.jpg  176.jpg  212.jpg  25.jpg   287.jpg  323.jpg  360.jpg	70.jpg
102.jpg  14.jpg   177.jpg  213.jpg  250.jpg  288.jpg  324.jpg  361.jpg	71.jpg
103.jpg  140.jpg  178.jpg  214.jpg  251.jpg  289.jpg  325.jpg  362.jpg	72.jpg
104.jpg  141.jpg  179.jpg  215.jpg  252.jpg  29.jpg   326.jpg  363.jpg	73.jpg
105.jpg  142.jpg  18.jpg   216.jpg  253.jpg  290.jpg  327.jpg  37.jpg	74.jpg
106.jpg  143.jpg  180.jpg  217.jpg  254.jpg  291.jpg  328.jpg  38.jpg	75.jpg
107.jpg  144.jpg  181.jpg  218.jpg  255.jpg  292.jpg  329.jpg  39.jpg	76.jpg
108.jpg  145.jpg  182.jpg  219.jpg  256.jpg  293.jpg  33.jpg   4.jpg	77.jpg
109.jpg  146.jpg  183.jpg  22.jpg   257.jpg  294.jpg  330.jpg  40.jpg	78.jpg
11.jpg	 147.jpg  184.jpg  220.jpg  258.jpg  295.jpg  331.jpg  41.jpg	79.jpg
110.jpg  148.jpg  185.jpg  221.jpg  259.jpg  296.jpg  332.jpg  42.jpg	8.jpg
111.jpg  149.jpg  186.jpg  222.jpg  26.jpg   297.jpg  333.jpg  43.jpg	80.jpg
112.jpg  15.jpg   187.jpg  223.jpg  260.jpg  298.jpg  334.jpg  44.jpg	81.jpg
113.jpg  150.jpg  188.jpg  224.jpg  261.jpg  299.jpg  335.jpg  45.jpg	82.jpg
114.jpg  151.jpg  189.jpg  225.jpg  262.jpg  3.jpg    336.jpg  46.jpg	83.jpg
115.jpg  152.jpg  19.jpg   226.jpg  263.jpg  30.jpg   337.jpg  47.jpg	84.jpg
116.jpg  153.jpg  190.jpg  227.jpg  264.jpg  300.jpg  338.jpg  48.jpg	85.jpg
117.jpg  154.jpg  191.jpg  228.jpg  265.jpg  301.jpg  339.jpg  49.jpg	86.jpg
118.jpg  155.jpg  192.jpg  229.jpg  266.jpg  302.jpg  34.jpg   5.jpg	87.jpg
119.jpg  156.jpg  193.jpg  23.jpg   267.jpg  303.jpg  340.jpg  50.jpg	88.jpg
12.jpg	 157.jpg  194.jpg  230.jpg  268.jpg  304.jpg  341.jpg  51.jpg	89.jpg
120.jpg  158.jpg  195.jpg  231.jpg  269.jpg  305.jpg  342.jpg  52.jpg	9.jpg
121.jpg  159.jpg  196.jpg  232.jpg  27.jpg   306.jpg  343.jpg  53.jpg	90.jpg
122.jpg  16.jpg   197.jpg  233.jpg  270.jpg  307.jpg  344.jpg  54.jpg	91.jpg
123.jpg  160.jpg  198.jpg  234.jpg  271.jpg  308.jpg  345.jpg  55.jpg	92.jpg
124.jpg  161.jpg  199.jpg  235.jpg  272.jpg  309.jpg  346.jpg  56.jpg	93.jpg
125.jpg  162.jpg  2.jpg    236.jpg  273.jpg  31.jpg   347.jpg  57.jpg	94.jpg
126.jpg  163.jpg  20.jpg   237.jpg  274.jpg  310.jpg  348.jpg  58.jpg	95.jpg
127.jpg  164.jpg  200.jpg  238.jpg  275.jpg  311.jpg  349.jpg  59.jpg	96.jpg
128.jpg  165.jpg  201.jpg  239.jpg  276.jpg  312.jpg  35.jpg   6.jpg	97.jpg
129.jpg  166.jpg  202.jpg  24.jpg   277.jpg  313.jpg  350.jpg  60.jpg	98.jpg
13.jpg	 167.jpg  203.jpg  240.jpg  278.jpg  314.jpg  351.jpg  61.jpg	99.jpg
130.jpg  168.jpg  204.jpg  241.jpg  279.jpg  315.jpg  352.jpg  62.jpg
131.jpg  169.jpg  205.jpg  242.jpg  28.jpg   316.jpg  353.jpg  63.jpg
132.jpg  17.jpg   206.jpg  243.jpg  280.jpg  317.jpg  354.jpg  64.jpg
133.jpg  170.jpg  207.jpg  244.jpg  281.jpg  318.jpg  355.jpg  65.jpg
134.jpg  171.jpg  208.jpg  245.jpg  282.jpg  319.jpg  356.jpg  66.jpg

In [18]:
len(no_face)

36

In [19]:
len(with_face)

364

In [20]:
%cd ..

/kaggle/working/test_images

In [21]:
%cd ..

/kaggle/working

In [22]:
model = MesoInception4()
model.load("/kaggle/input/meso-pretrain/MesoInception_DF")

In [23]:
from keras.preprocessing.image import ImageDataGenerator

image_data_generator = ImageDataGenerator(rescale=1.0/255)
data_generator = image_data_generator.flow_from_directory("test_images",classes=["image_class"],batch_size=364) 

""" Here test_images folder will contain another dolder having any name
    That folder will contain all the test images we will work on
"""

Found 364 images belonging to 1 classes.

' Here test_images folder will contain another dolder having any name\n    That folder will contain all the test images we will work on\n'

In [24]:
X,y = data_generator.next()

In [25]:
len(X)

364

In [26]:
probablistic_predictions = model.predict(X)

In [27]:
print(probablistic_predictions)

[[3.57530296e-01]
 [1.00000000e+00]
 [9.99046028e-01]
 [1.00000000e+00]
 [6.69506431e-01]
 [1.00000000e+00]
 [3.28371227e-02]
 [8.04284513e-01]
 [9.74353552e-01]
 [8.80600810e-01]
 [9.96803701e-01]
 [3.16811502e-02]
 [1.00000000e+00]
 [9.99997854e-01]
 [4.48970795e-02]
 [9.99980211e-01]
 [2.58901328e-01]
 [1.00000000e+00]
 [9.99999762e-01]
 [9.99999881e-01]
 [1.12329721e-02]
 [9.92709160e-01]
 [1.65021718e-02]
 [9.88470018e-01]
 [9.97613728e-01]
 [9.99987900e-01]
 [9.98224139e-01]
 [1.00000000e+00]
 [9.88342404e-01]
 [3.89740467e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.99817729e-01]
 [6.42713726e-01]
 [9.99997377e-01]
 [1.00000000e+00]
 [9.99922037e-01]
 [9.99414325e-01]
 [5.38041532e-01]
 [9.87967491e-01]
 [9.86591101e-01]
 [9.99832451e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.99990582e-01]
 [8.36002767e-01]
 [9.99967813e-01]
 [5.72889328e-01]
 [5.58596671e-01]
 [9.99854982e-01]
 [9.71654296e-01]
 [2.11377650e-01]
 [6.59201443e-01]
 [5.99537373e-01]
 [9.88856554e-01]
 [6.61140323e-01]
 [1.73224211e-02]
 [9.99861002e-01]
 [9.99987304e-01]
 [9.93468285e-01]
 [1.00000000e+00]
 [4.39126551e-01]
 [1.00000000e+00]
 [9.98911977e-01]
 [9.81317759e-01]
 [9.69679058e-01]
 [9.99981523e-01]
 [8.56572986e-01]
 [5.91500342e-01]
 [7.99438238e-01]
 [9.99976933e-01]
 [2.79004276e-02]
 [9.99997854e-01]
 [1.00000000e+00]
 [4.55796719e-04]
 [9.51021194e-01]
 [9.94097352e-01]
 [9.99577761e-01]
 [1.00000000e+00]
 [1.65241539e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.96880174e-01]
 [1.00000000e+00]
 [9.99999523e-01]
 [9.99197721e-01]
 [9.78781700e-01]
 [9.83921289e-01]
 [3.65460813e-01]
 [3.71294022e-01]
 [6.52829528e-01]
 [9.99994636e-01]
 [2.17143983e-01]
 [9.88265276e-01]
 [6.48113906e-01]
 [9.81639445e-01]
 [8.86275530e-01]
 [2.51217902e-01]
 [5.86261988e-01]
 [2.43186951e-05]
 [1.00000000e+00]
 [9.96401846e-01]
 [9.97775674e-01]
 [7.05029428e-01]
 [9.67980683e-01]
 [1.28927827e-03]
 [7.85249710e-01]
 [6.32119596e-01]
 [9.64730918e-01]
 [5.32852829e-01]
 [9.98343349e-01]
 [1.22367084e-01]
 [3.13314795e-03]
 [9.99998808e-01]
 [9.50309157e-01]
 [1.00000000e+00]
 [7.18628883e-01]
 [3.50875914e-01]
 [9.99922514e-01]
 [9.99999762e-01]
 [5.48941135e-01]
 [9.99973893e-01]
 [3.38230401e-01]
 [9.91434574e-01]
 [7.36046374e-01]
 [3.06475699e-01]
 [4.41660345e-01]
 [8.82649243e-01]
 [5.73992014e-01]
 [9.95812178e-01]
 [9.98718500e-01]
 [9.99934077e-01]
 [3.90016705e-01]
 [9.61506188e-01]
 [9.94082808e-01]
 [9.59245563e-01]
 [9.99963403e-01]
 [9.99955773e-01]
 [3.70378256e-01]
 [7.46200979e-01]
 [1.00000000e+00]
 [9.99076128e-01]
 [5.44077694e-01]
 [9.99989510e-01]
 [5.08294582e-01]
 [4.90351260e-01]
 [9.99529600e-01]
 [7.19635606e-01]
 [7.32059479e-01]
 [9.99970198e-01]
 [9.75112021e-01]
 [9.99951482e-01]
 [2.44475603e-01]
 [1.46031380e-06]
 [4.48608458e-01]
 [7.44211614e-01]
 [3.46451342e-01]
 [9.99938130e-01]
 [7.44232833e-02]
 [5.06145716e-01]
 [2.62260437e-05]
 [6.53069675e-01]
 [1.00000000e+00]
 [9.57224250e-01]
 [7.38429964e-01]
 [2.82646179e-01]
 [9.93941247e-01]
 [1.42371297e-01]
 [1.00000000e+00]
 [9.48746979e-01]
 [6.78314507e-01]
 [9.99999583e-01]
 [5.37298143e-01]
 [9.41554070e-01]
 [9.99683499e-01]
 [9.99957860e-01]
 [5.24406075e-01]
 [7.43261456e-01]
 [9.99964237e-01]
 [9.99997973e-01]
 [9.97952461e-01]
 [4.30004299e-02]
 [1.00000000e+00]
 [9.94091332e-01]
 [9.88775849e-01]
 [1.00000000e+00]
 [2.02678859e-01]
 [6.24396503e-01]
 [8.90073895e-01]
 [9.97512817e-01]
 [3.26828301e-01]
 [6.61770523e-01]
 [9.99573946e-01]
 [4.77366626e-01]
 [9.51898575e-01]
 [9.96974587e-01]
 [1.98737264e-01]
 [8.16610575e-01]
 [5.22709727e-01]
 [5.01961172e-01]
 [5.41021466e-01]
 [4.49957788e-01]
 [3.56691480e-01]
 [7.49721766e-01]
 [4.78648692e-01]
 [8.36634159e-01]
 [6.93850696e-01]
 [3.94885063e-01]
 [9.91919041e-01]
 [7.43960202e-01]
 [4.20851797e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [7.65684485e-01]
 [7.02229202e-01]
 [9.99129832e-01]
 [9.99594927e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.99835193e-01]
 [5.48848808e-01]
 [9.99994278e-01]
 [9.67780769e-01]
 [9.99965072e-01]
 [9.99950528e-01]
 [9.99995351e-01]
 [1.76594049e-01]
 [4.06873226e-03]
 [9.99951065e-01]
 [1.00000000e+00]
 [9.99999762e-01]
 [5.57146490e-01]
 [1.00000000e+00]
 [4.98878956e-03]
 [1.00000000e+00]
 [9.99999881e-01]
 [5.81475735e-01]
 [1.15081817e-01]
 [7.51964569e-01]
 [1.66893005e-06]
 [3.18655670e-01]
 [8.97227228e-01]
 [4.09787297e-02]
 [2.19643295e-01]
 [8.13351810e-01]
 [6.22905850e-01]
 [4.77452427e-01]
 [8.46385956e-06]
 [8.05535913e-01]
 [4.18383360e-01]
 [1.00000000e+00]
 [2.91899204e-01]
 [9.99881387e-01]
 [5.20202398e-01]
 [9.99999881e-01]
 [2.66502559e-01]
 [9.37035441e-01]
 [9.99998808e-01]
 [8.47759008e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.98014331e-01]
 [7.96775699e-01]
 [3.25874776e-01]
 [9.67068195e-01]
 [7.16571212e-01]
 [7.97932267e-01]
 [9.99548554e-01]
 [6.27314448e-01]
 [1.00000000e+00]
 [3.37799489e-02]
 [8.81100595e-01]
 [5.91028333e-01]
 [9.85985696e-01]
 [5.03742695e-02]
 [6.24019504e-02]
 [9.97933745e-03]
 [4.36214507e-02]
 [1.00000000e+00]
 [5.64140022e-01]
 [9.98119235e-01]
 [9.99987841e-01]
 [6.77215576e-01]
 [9.14318502e-01]
 [6.22056723e-01]
 [1.00000000e+00]
 [4.51053888e-01]
 [1.00000000e+00]
 [6.87290728e-01]
 [9.99999940e-01]
 [9.99695182e-01]
 [9.99999821e-01]
 [9.90501761e-01]
 [5.27722061e-01]
 [1.12496227e-01]
 [9.98753428e-01]
 [1.44073665e-02]
 [3.30699980e-02]
 [9.98775721e-01]
 [1.00000000e+00]
 [4.55776483e-01]
 [1.00000000e+00]
 [9.99969721e-01]
 [1.00000000e+00]
 [9.99999583e-01]
 [9.50787663e-01]
 [1.00000000e+00]
 [9.99999881e-01]
 [9.99968290e-01]
 [6.26511037e-01]
 [6.70748532e-01]
 [9.40679610e-01]
 [9.98156130e-01]
 [7.42086053e-01]
 [9.97130096e-01]
 [1.00000000e+00]
 [6.24649525e-01]
 [1.00000000e+00]
 [9.58507776e-01]
 [9.99444962e-01]
 [1.00000000e+00]
 [9.99935389e-01]
 [9.99999166e-01]
 [1.00000000e+00]
 [7.63818979e-01]
 [9.99968112e-01]
 [1.52139127e-01]
 [9.99979258e-01]
 [6.56342626e-01]
 [9.99948561e-01]
 [3.85980129e-01]
 [9.97909427e-01]
 [5.08858860e-02]
 [1.00000000e+00]
 [9.99999225e-01]
 [3.89036447e-01]
 [6.79763079e-01]
 [4.75301355e-01]
 [3.23892832e-01]
 [3.56522501e-02]
 [9.99847293e-01]
 [9.90105391e-01]
 [2.29508281e-02]
 [5.31697929e-01]
 [5.53383529e-01]
 [9.97945607e-01]
 [9.99985278e-01]
 [1.00000000e+00]
 [3.68766129e-01]
 [9.99976993e-01]
 [2.25156546e-04]
 [1.00000000e+00]
 [9.01593089e-01]
 [6.07898831e-03]
 [1.00000000e+00]
 [3.27192605e-01]
 [9.99999642e-01]
 [6.31809235e-06]
 [9.72412586e-01]
 [4.88572806e-01]
 [1.28707886e-01]
 [9.99994576e-01]
 [9.74827409e-01]]

In [28]:
import pandas as pd
sample_submission = pd.read_csv("../input/deepfake-detection-challenge/sample_submission.csv")

In [29]:
submission = pd.read_csv(os.path.join(INPUT, "sample_submission.csv"))
# fill in 0.5 for no face use
submission["label"] = 0.5
submission.head()

         filename  label
0  aassnaulhq.mp4    0.5
1  aayfryxljh.mp4    0.5
2  acazlolrpz.mp4    0.5
3  adohdulfwb.mp4    0.5
4  ahjnxtiamx.mp4    0.5

In [30]:
preds = probablistic_predictions

In [31]:
type(preds)

numpy.ndarray

In [32]:
type(submission)

pandas.core.frame.DataFrame

In [33]:
len(preds)

364

In [34]:
len(submission)

400

In [35]:
# convert submission to numpy.ndarray
sub = submission.values

In [36]:
len(sub)

400

In [37]:
with_face_a = np.asarray(with_face)

In [38]:
with_face_a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  35,  36,  37,  38,  39,  40,
        41,  43,  44,  46,  47,  48,  49,  50,  51,  52,  53,  55,  56,
        57,  58,  59,  60,  61,  62,  64,  65,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 124, 125, 126,
       127, 129, 130, 131, 132, 133, 134, 135, 136, 138, 139, 140, 141,
       142, 143, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 159, 160, 161, 162, 163, 164, 165, 166, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 182, 183, 184,
       185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 196, 197, 198,
       199, 200, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 220, 221, 222, 223, 224, 226, 227,
       228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
       241, 242, 243, 244, 247, 248, 249, 250, 251, 252, 254, 255, 256,
       257, 258, 259, 260, 261, 262, 264, 265, 266, 268, 269, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 296, 297, 298, 299, 300,
       301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313,
       314, 316, 317, 318, 319, 321, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 347, 348, 349, 350, 352, 353, 354, 355, 356, 357, 358,
       359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 370, 371, 372,
       373, 374, 375, 376, 377, 378, 379, 380, 382, 383, 384, 385, 386,
       387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399])

In [39]:
for c in range(len(with_face)):
    x = with_face[c]
    sub[x][1] = preds[c][0]

In [40]:
len(sub)

400

In [41]:
type(sub)

numpy.ndarray

In [42]:
sub

array([['aassnaulhq.mp4', 0.3575303],
       ['aayfryxljh.mp4', 1.0],
       ['acazlolrpz.mp4', 0.999046],
       ['adohdulfwb.mp4', 1.0],
       ['ahjnxtiamx.mp4', 0.66950643],
       ['ajiyrjfyzp.mp4', 1.0],
       ['aktnlyqpah.mp4', 0.032837123],
       ['alrtntfxtd.mp4', 0.8042845],
       ['aomqqjipcp.mp4', 0.97435355],
       ['apedduehoy.mp4', 0.8806008],
       ['apvzjkvnwn.mp4', 0.9968037],
       ['aqrsylrzgi.mp4', 0.03168115],
       ['axfhbpkdlc.mp4', 0.5],
       ['ayipraspbn.mp4', 1.0],
       ['bcbqxhziqz.mp4', 0.99999785],
       ['bcvheslzrq.mp4', 0.04489708],
       ['bdshuoldwx.mp4', 0.9999802],
       ['bfdopzvxbi.mp4', 0.25890133],
       ['bfjsthfhbd.mp4', 1.0],
       ['bjyaxvggle.mp4', 0.99999976],
       ['bkcyglmfci.mp4', 0.9999999],
       ['bktkwbcawi.mp4', 0.011232972],
       ['bkuzquigyt.mp4', 0.99270916],
       ['blnmxntbey.mp4', 0.016502172],
       ['blszgmxkvu.mp4', 0.98847],
       ['bnuwxhfahw.mp4', 0.9976137],
       ['bofrwgeyjo.mp4', 0.9999879],
       ['btdxnajogv.mp4', 0.99822414],
       ['bvpeerislp.mp4', 1.0],
       ['bwdmzwhdnw.mp4', 0.9883424],
       ['bzvzpwrabw.mp4', 0.038974047],
       ['cekarydqba.mp4', 1.0],
       ['cekwtyxdoo.mp4', 1.0],
       ['cjkctqqakb.mp4', 0.9998177],
       ['cnpanmywno.mp4', 0.5],
       ['cnxccbjlct.mp4', 0.6427137],
       ['coqwgzpbhx.mp4', 0.9999974],
       ['cosghhimnd.mp4', 1.0],
       ['coujjnypba.mp4', 0.99992204],
       ['cqhwesrciw.mp4', 0.9994143],
       ['cqxxumarvp.mp4', 0.53804153],
       ['csnkohqxdv.mp4', 0.9879675],
       ['cxsvvnxpyz.mp4', 0.5],
       ['czfqlbcfpa.mp4', 0.9865911],
       ['dcqodpzomd.mp4', 0.99983245],
       ['ddtbarpcgo.mp4', 0.5],
       ['demuhxssgl.mp4', 1.0],
       ['didzujjhtg.mp4', 1.0],
       ['dkuqbduxev.mp4', 0.9999906],
       ['dmmvuaikkv.mp4', 0.83600277],
       ['dnmowthjcj.mp4', 0.9999678],
       ['doniqevxeg.mp4', 0.5728893],
       ['dozjwhnedd.mp4', 0.5585967],
       ['dpevefkefv.mp4', 0.999855],
       ['dpmgoiwhuf.mp4', 0.5],
       ['dsnxgrfdmd.mp4', 0.9716543],
       ['dtozwcapoa.mp4', 0.21137765],
       ['dvkdfhrpph.mp4', 0.65920144],
       ['dvtpwatuja.mp4', 0.5995374],
       ['dvwpvqdflx.mp4', 0.98885655],
       ['dxfdovivlw.mp4', 0.6611403],
       ['dxgnpnowgk.mp4', 0.017322421],
       ['dyjklprkoc.mp4', 0.999861],
       ['dzkyxbbqkr.mp4', 0.5],
       ['dzojiwfvba.mp4', 0.9999873],
       ['ecumyiowzs.mp4', 0.9934683],
       ['eisofhptvk.mp4', 0.5],
       ['ekboxwrwuv.mp4', 1.0],
       ['ekelfsnqof.mp4', 0.43912655],
       ['ekvwecwltj.mp4', 1.0],
       ['elackxuccp.mp4', 0.998912],
       ['eppyqpgewp.mp4', 0.98131776],
       ['eqslzbqfea.mp4', 0.96967906],
       ['eryjktdexi.mp4', 0.9999815],
       ['esjdyghhog.mp4', 0.856573],
       ['esmqxszybs.mp4', 0.59150034],
       ['espkiocpxq.mp4', 0.79943824],
       ['etdliwticv.mp4', 0.99997693],
       ['evysmtpnrf.mp4', 0.027900428],
       ['eyguqfmgzh.mp4', 0.99999785],
       ['eywdmustbb.mp4', 0.5],
       ['famlupsgqm.mp4', 1.0],
       ['fddmkqjwsh.mp4', 0.00045579672],
       ['fjrueenjyp.mp4', 0.9510212],
       ['fjxovgmwnm.mp4', 0.99409735],
       ['fmhiujydwo.mp4', 0.99957776],
       ['fmvvmcbdrw.mp4', 1.0],
       ['fneqiqpqvs.mp4', 0.16524154],
       ['fnxgqcvlsd.mp4', 1.0],
       ['fopjiyxiqd.mp4', 1.0],
       ['fpevfidstw.mp4', 1.0],
       ['fqgypsunzr.mp4', 0.9968802],
       ['frqfsucgao.mp4', 1.0],
       ['fsdrwikhge.mp4', 0.9999995],
       ['fwykevubzy.mp4', 0.9991977],
       ['fxuxxtryjn.mp4', 0.9787817],
       ['fzvpbrzssi.mp4', 0.9839213],
       ['gahgyuwzbu.mp4', 0.3654608],
       ['gbnzicjyhz.mp4', 0.37129402],
       ['gccnvdoknm.mp4', 0.6528295],
       ['gcdtglsoqj.mp4', 0.99999464],
       ['gfcycflhbo.mp4', 0.21714398],
       ['gfdjzwnpyp.mp4', 0.5],
       ['gfgcwxkbjd.mp4', 0.9882653],
       ['ggdpclfcgk.mp4', 0.6481139],
       ['ggzjfrirjh.mp4', 0.98163944],
       ['ghnpsltzyn.mp4', 0.88627553],
       ['gkutjglghz.mp4', 0.2512179],
       ['gochxzemmq.mp4', 0.586262],
       ['gpsxfxrjrr.mp4', 2.4318695e-05],
       ['gqnaxievjx.mp4', 1.0],
       ['gunamloolc.mp4', 0.99640185],
       ['halvwiltfs.mp4', 0.9977757],
       ['hbufmvbium.mp4', 0.7050294],
       ['hcanfkwivl.mp4', 0.9679807],
       ['hclsparpth.mp4', 0.0012892783],
       ['hefisnapds.mp4', 0.7852497],
       ['heiyoojifp.mp4', 0.6321196],
       ['hevcclcklc.mp4', 0.9647309],
       ['hfsvqabzfq.mp4', 0.5],
       ['hicjuubiau.mp4', 0.5328528],
       ['hierggamuo.mp4', 0.99834335],
       ['hitfycdavv.mp4', 0.122367084],
       ['hnfwagcxdf.mp4', 0.003133148],
       ['honxqdilvv.mp4', 0.9999988],
       ['hqzwudvhih.mp4', 0.95030916],
       ['hsbljbsgxr.mp4', 1.0],
       ['hsbwhlolsn.mp4', 0.7186289],
       ['hszwwswewp.mp4', 0.5],
       ['htzbnroagi.mp4', 0.3508759],
       ['huvlwkxoxm.mp4', 0.9999225],
       ['hweshqpfwe.mp4', 0.99999976],
       ['hxwtsaydal.mp4', 0.54894114],
       ['hyjqolupxn.mp4', 0.9999739],
       ['hzoiotcykp.mp4', 0.3382304],
       ['hzssdinxec.mp4', 0.9914346],
       ['ibxfxggtqh.mp4', 0.7360464],
       ['icbsahlivv.mp4', 0.5],
       ['igpvrfjdzc.mp4', 0.3064757],
       ['ihglzxzroo.mp4', 0.44166034],
       ['iksxzpqxzi.mp4', 0.88264924],
       ['ilqwcbprqa.mp4', 0.573992],
       ['imdmhwkkni.mp4', 0.9958122],
       ['iorbtaarte.mp4', 0.9987185],
       ['ipkpxvwroe.mp4', 0.5],
       ['ipvwtgdlre.mp4', 0.9999341],
       ['irqzdokcws.mp4', 0.3900167],
       ['itfsvvmslp.mp4', 0.9615062],
       ['iznnzjvaxc.mp4', 0.9940828],
       ['jawgcggquk.mp4', 0.95924556],
       ['jhczqfefgw.mp4', 0.9999634],
       ['jiavqbrkyk.mp4', 0.9999558],
       ['jiswxuqzyz.mp4', 0.37037826],
       ['jquevmhdvc.mp4', 0.746201],
       ['jsbpkpxwew.mp4', 1.0],
       ['jsysgmycsx.mp4', 0.9990761],
       ['jyfvaequfg.mp4', 0.5440777],
       ['jyoxdvxpza.mp4', 0.9999895],
       ['jytrvwlewz.mp4', 0.5],
       ['jzmzdispyo.mp4', 0.5082946],
       ['kcjvhgvhpt.mp4', 0.49035126],
       ['keioymnobc.mp4', 0.9995296],
       ['kezwvsxxzj.mp4', 0.7196356],
       ['khpipxnsvx.mp4', 0.7320595],
       ['kmcdjxmnoa.mp4', 0.9999702],
       ['kmqkiihrmj.mp4', 0.975112],
       ['knxltsvzyu.mp4', 0.9999515],
       ['kowiwvrjht.mp4', 0.5],
       ['kqlvggiqee.mp4', 0.2444756],
       ['kvmpmhdxly.mp4', 1.4603138e-06],
       ['kwfdyqofzw.mp4', 0.44860846],
       ['lbfqksftuo.mp4', 0.7442116],
       ['lbigytrrtr.mp4', 0.34645134],
       ['lebzjtusnr.mp4', 0.99993813],
       ['lhvjzhjxdp.mp4', 0.07442328],
       ['ljauauuyka.mp4', 0.5061457],
       ['ljouzjaqqe.mp4', 2.6226044e-05],
       ['llplvmcvbl.mp4', 0.6530697],
       ['lmdyicksrv.mp4', 1.0],
       ['lnhkjhyhvw.mp4', 0.95722425],
       ['lnjkpdviqb.mp4', 0.73842996],
       ['lpgxwdgnio.mp4', 0.5],
       ['lpkgabskbw.mp4', 0.28264618],
       ['lujvyveojc.mp4', 0.99394125],
       ['lyoslorecs.mp4', 0.1423713],
       ['mdfndlljvt.mp4', 1.0],
       ['mkmgcxaztt.mp4', 0.948747],
       ['mkzaekkvej.mp4', 0.6783145],
       ['mllzkpgatp.mp4', 0.9999996],
       ['mnowxangqx.mp4', 0.53729814],
       ['mnzabbkpmt.mp4', 0.94155407],
       ['mohiqoogpb.mp4', 0.9996835],
       ['mszblrdprw.mp4', 0.99995786],
       ['mwnibuujwz.mp4', 0.5244061],
       ['mwwploizlj.mp4', 0.74326146],
       ['mxahsihabr.mp4', 0.5],
       ['mxlipjhmqk.mp4', 0.99996424],
       ['ncmpqwmnzb.mp4', 0.999998],
       ['ncoeewrdlo.mp4', 0.99795246],
       ['ndikguxzek.mp4', 0.04300043],
       ['nikynwcvuh.mp4', 1.0],
       ['njzshtfmcw.mp4', 0.5],
       ['nkhzxomani.mp4', 0.99409133],
       ['novarhxpbj.mp4', 0.98877585],
       ['nplviymzlg.mp4', 1.0],
       ['nswtvttxre.mp4', 0.20267886],
       ['nthpnwylxo.mp4', 0.6243965],
       ['nwvloufjty.mp4', 0.8900739],
       ['nwvsbmyndn.mp4', 0.9975128],
       ['nxgzmgzkfv.mp4', 0.3268283],
       ['nxnmkytwze.mp4', 0.6617705],
       ['nxzgekegsp.mp4', 0.99957395],
       ['nycmyuzpml.mp4', 0.47736663],
       ['nymodlmxni.mp4', 0.9518986],
       ['oaguiggjyv.mp4', 0.9969746],
       ['ocgdbrgmtq.mp4', 0.19873726],
       ['oefukgnvel.mp4', 0.8166106],
       ['oelqpetgwj.mp4', 0.5227097],
       ['ojsxxkalat.mp4', 0.5019612],
       ['okgelildpc.mp4', 0.5],
       ['omphqltjdd.mp4', 0.54102147],
       ['ooafcxxfrs.mp4', 0.4499578],
       ['oocincvedt.mp4', 0.35669148],
       ['oojxonbgow.mp4', 0.74972177],
       ['opvqdabdap.mp4', 0.4786487],
       ['orekjthsef.mp4', 0.5],
       ['orixbcfvdz.mp4', 0.83663416],
       ['ouaowjmigq.mp4', 0.6938507],
       ['owaogcehvc.mp4', 0.39488506],
       ['oyqgwjdwaj.mp4', 0.99191904],
       ['oysopgovhu.mp4', 0.7439602],
       ['papagllumt.mp4', 0.4208518],
       ['pcoxcmtroa.mp4', 1.0],
       ['pcyswtgick.mp4', 1.0],
       ['pdswwyyntw.mp4', 0.7656845],
       ['pdufsewrec.mp4', 0.7022292],
       ['petmyhjclt.mp4', 0.99912983],
       ['phjvutxpoi.mp4', 0.9995949],
       ['pqdeutauqc.mp4', 1.0],
       ['pqthmvwonf.mp4', 1.0],
       ['prhmixykhr.mp4', 0.9998352],
       ['prwsfljdjo.mp4', 0.5488488],
       ['psesikjaxx.mp4', 0.9999943],
       ['ptbfnkajyi.mp4', 0.96778077],
       ['ptbnewtvon.mp4', 0.9999651],
       ['pxcfrszlgi.mp4', 0.5],
       ['pxjkzvqomp.mp4', 0.5],
       ['qarqtkvgby.mp4', 0.9999505],
       ['qcbkztamqc.mp4', 0.99999535],
       ['qclpbcbgeq.mp4', 0.17659405],
       ['qdqdsaiitt.mp4', 0.0040687323],
       ['qhkzlnzruj.mp4', 0.99995106],
       ['qhsehzgxqj.mp4', 1.0],
       ['qlqhjcshpk.mp4', 0.5],
       ['qlvsqdroqo.mp4', 0.99999976],
       ['qooxnxqqjb.mp4', 0.5571465],
       ['qqnlrngaft.mp4', 1.0],
       ['qsjiypnjwi.mp4', 0.0049887896],
       ['qswlzfgcgj.mp4', 1.0],
       ['qxyrtwozyw.mp4', 0.9999999],
       ['qyyhuvqmyf.mp4', 0.58147573],
       ['rcecrgeotc.mp4', 0.11508182],
       ['rcjfxxhcal.mp4', 0.75196457],
       ['rerpivllud.mp4', 0.5],
       ['rfjuhbnlro.mp4', 1.66893e-06],
       ['rfwxcinshk.mp4', 0.31865567],
       ['rklawjhbpv.mp4', 0.8972272],
       ['rktrpsdlci.mp4', 0.5],
       ['rmlzgerevr.mp4', 0.04097873],
       ['rmufsuogzn.mp4', 0.2196433],
       ['rnfcjxynfa.mp4', 0.5],
       ['rrrfjhugvb.mp4', 0.8133518],
       ['rtpbawlmxr.mp4', 0.62290585],
       ['ruhtnngrqv.mp4', 0.47745243],
       ['rukyxomwcx.mp4', 8.46386e-06],
       ['rvvpazsffd.mp4', 0.8055359],
       ['rxdoimqble.mp4', 0.41838336],
       ['ryxaqpfubf.mp4', 1.0],
       ['scbdenmaed.mp4', 0.2918992],
       ['scrbqgpvzz.mp4', 0.9998814],
       ['sfsayjgzrh.mp4', 0.5202024],
       ['shnsajrsow.mp4', 0.9999999],
       ['siebfpwuhu.mp4', 0.5],
       ['sjinmmbipg.mp4', 0.26650256],
       ['sjkfxrlxxs.mp4', 0.93703544],
       ['sjwywglgym.mp4', 0.9999988],
       ['sktpeppbkc.mp4', 0.847759],
       ['sngjsueuhs.mp4', 1.0],
       ['snlyjbnpgw.mp4', 1.0],
       ['sodvtfqbpf.mp4', 0.99801433],
       ['sqixhnilfm.mp4', 0.7967757],
       ['srfefmyjvt.mp4', 0.32587478],
       ['sufvvwmbha.mp4', 0.9670682],
       ['swsaoktwgi.mp4', 0.7165712],
       ['sylnrepacf.mp4', 0.79793227],
       ['syuxttuyhm.mp4', 0.5],
       ['syxobtuucp.mp4', 0.99954855],
       ['sznkemeqro.mp4', 0.62731445],
       ['tejfudfgpq.mp4', 1.0],
       ['temeqbmzxu.mp4', 0.03377995],
       ['temjefwaas.mp4', 0.8811006],
       ['tgawasvbbr.mp4', 0.59102833],
       ['tjuihawuqm.mp4', 0.9859857],
       ['tjywwgftmv.mp4', 0.05037427],
       ['toinozytsp.mp4', 0.06240195],
       ['tvhjcfnqtg.mp4', 0.009979337],
       ['txmnoyiyte.mp4', 0.04362145],
       ['txnmkabufs.mp4', 1.0],
       ['tyjpjpglgx.mp4', 0.56414],
       ['tynfsthodx.mp4', 0.99811924],
       ['ucthmsajay.mp4', 0.99998784],
       ['udxqbhgvvx.mp4', 0.6772156],
       ['uhakqelqri.mp4', 0.9143185],
       ['uhrqlmlclw.mp4', 0.6220567],
       ['uoccaiathd.mp4', 1.0],
       ['upmgtackuf.mp4', 0.5],
       ['uqvxjfpwdo.mp4', 0.4510539],
       ['usqqvxcjmg.mp4', 1.0],
       ['uubgqnvfdl.mp4', 0.6872907],
       ['uvrzaczrbx.mp4', 0.99999994],
       ['uxuvkrjhws.mp4', 0.5],
       ['vajkicalux.mp4', 0.9996952],
       ['vbcgoyxsvn.mp4', 0.5],
       ['vdtsbqidjb.mp4', 0.9999998],
       ['vhbbwdflyh.mp4', 0.99050176],
       ['viteugozpv.mp4', 0.52772206],
       ['vizerpsvbz.mp4', 0.11249623],
       ['vjljdfopjg.mp4', 0.9987534],
       ['vmxfwxgdei.mp4', 0.0144073665],
       ['vnlzxqwthl.mp4', 0.033069998],
       ['voawxrmqyl.mp4', 0.9987757],
       ['vokrpfjpeb.mp4', 1.0],
       ['vssmlqoiti.mp4', 0.45577648],
       ['vtunvalyji.mp4', 1.0],
       ['vurjckblge.mp4', 0.9999697],
       ['vvfszaosiv.mp4', 1.0],
       ['vwxednhlwz.mp4', 0.9999996],
       ['wadvzjhwtw.mp4', 0.95078766],
       ['waucvvmtkq.mp4', 1.0],
       ['wclvkepakb.mp4', 0.9999999],
       ['wcqvzujamg.mp4', 0.9999683],
       ['wcssbghcpc.mp4', 0.62651104],
       ['wcvsqnplsk.mp4', 0.67074853],
       ['wfzjxzhdkj.mp4', 0.9406796],
       ['wixbuuzygv.mp4', 0.99815613],
       ['wjhpisoeaj.mp4', 0.5],
       ['wmoqzxddkb.mp4', 0.5],
       ['wndursivcx.mp4', 0.74208605],
       ['wnlubukrki.mp4', 0.9971301],
       ['wqysrieiqu.mp4', 1.0],
       ['wvgviwnwob.mp4', 0.6246495],
       ['wynotylpnm.mp4', 0.5],
       ['xcruhaccxc.mp4', 1.0],
       ['xdezcezszc.mp4', 0.9585078],
       ['xhtppuyqdr.mp4', 0.99944496],
       ['xitgdpzbxv.mp4', 1.0],
       ['xjvxtuakyd.mp4', 0.9999354],
       ['xljemofssi.mp4', 0.99999917],
       ['xmkwsnuzyq.mp4', 1.0],
       ['xphdfgmfmz.mp4', 0.763819],
       ['xrtvqhdibb.mp4', 0.9999681],
       ['xugmhbetrw.mp4', 0.15213913],
       ['xxzefxwyku.mp4', 0.99997926],
       ['yarpxfqejd.mp4', 0.6563426],
       ['yaxgpxhavq.mp4', 0.99994856],
       ['ybbrkacebd.mp4', 0.38598013],
       ['yhjlnisfel.mp4', 0.9979094],
       ['yhylappzid.mp4', 0.050885886],
       ['yietrwuncf.mp4', 1.0],
       ['yiykshcbaz.mp4', 0.5],
       ['yljecirelf.mp4', 0.9999992],
       ['yllztsrwjw.mp4', 0.38903645],
       ['ylxwcwhjjd.mp4', 0.6797631],
       ['yoyhmxtrys.mp4', 0.47530136],
       ['ypbtpunjvm.mp4', 0.32389283],
       ['yqhouqakbx.mp4', 0.03565225],
       ['yronlutbgm.mp4', 0.9998473],
       ['ystdtnetgj.mp4', 0.9901054],
       ['ytddugrwph.mp4', 0.022950828],
       ['ytopzxrswu.mp4', 0.5316979],
       ['ywauoonmlr.mp4', 0.5533835],
       ['ywxpquomgt.mp4', 0.5],
       ['yxadevzohx.mp4', 0.9979456],
       ['yxirnfyijn.mp4', 0.9999853],
       ['yxvmusxvcz.mp4', 1.0],
       ['yzuestxcbq.mp4', 0.36876613],
       ['zbgssotnjm.mp4', 0.999977],
       ['zcxcmneefk.mp4', 0.00022515655],
       ['zfobicuigx.mp4', 1.0],
       ['zfrrixsimm.mp4', 0.9015931],
       ['zgbhzkditd.mp4', 0.0060789883],
       ['zgjosltkie.mp4', 1.0],
       ['ziipxxchai.mp4', 0.3271926],
       ['zmxeiipnqb.mp4', 0.99999964],
       ['ztyuiqrhdk.mp4', 6.3180923e-06],
       ['ztyvglkcsf.mp4', 0.9724126],
       ['zuwwbbusgl.mp4', 0.4885728],
       ['zxacihctqp.mp4', 0.12870789],
       ['zyufpqvpyu.mp4', 0.9999946],
       ['zzmgnglanj.mp4', 0.9748274]], dtype=object)

In [43]:
sample_submission

           filename  label
0    aassnaulhq.mp4      0
1    aayfryxljh.mp4      0
2    acazlolrpz.mp4      0
3    adohdulfwb.mp4      0
4    ahjnxtiamx.mp4      0
..              ...    ...
395  ztyvglkcsf.mp4      0
396  zuwwbbusgl.mp4      0
397  zxacihctqp.mp4      0
398  zyufpqvpyu.mp4      0
399  zzmgnglanj.mp4      0

[400 rows x 2 columns]

In [44]:
sub_df = pd.DataFrame({'filename': sub[:, 0], 'label': sub[:, 1]})

In [45]:
sub_df

           filename     label
0    aassnaulhq.mp4   0.35753
1    aayfryxljh.mp4         1
2    acazlolrpz.mp4  0.999046
3    adohdulfwb.mp4         1
4    ahjnxtiamx.mp4  0.669506
..              ...       ...
395  ztyvglkcsf.mp4  0.972413
396  zuwwbbusgl.mp4  0.488573
397  zxacihctqp.mp4  0.128708
398  zyufpqvpyu.mp4  0.999995
399  zzmgnglanj.mp4  0.974827

[400 rows x 2 columns]

In [46]:
sub_df.to_csv("submission.csv", index=False)
sub_df.head()

         filename     label
0  aassnaulhq.mp4   0.35753
1  aayfryxljh.mp4         1
2  acazlolrpz.mp4  0.999046
3  adohdulfwb.mp4         1
4  ahjnxtiamx.mp4  0.669506